### ISSUE TITLE
Bug in RPC name service

### ISSUE THREAD

**Issue by RealJohnSmith** [nknorg/nkn#493] opened 2019-04-30 04:26 UTC
### Description of the issue

Registering and/or resolving a name to public key does not give correct results.

### Issue-Type (put a `x` sign in the square brackets)
- [x] bug report
- [ ] feature request
- [ ] Documentation improvement

### Checklist
- [x] Running latest version of the code.
- [x] This issue has not been reported earlier.

### Your environment
* OS: Not relevant
* Go version: Not relevant
* Release tag/commit of the code: ed50f2813980ec890cbc6981cd04f86019b686b0

### Expected behavior

Registering a name to the public key and then resolving this name should return the corresponding wallet address.

### Actual behavior

Registering a name to the public key and then resolving this name returns a different wallet address. One possible cause is a bug in encoding the public key to a wallet address, may be related to migration to Ed25519

### Steps to reproduce

(1) Send a transaction to register the name to a public key
(2) Request an NKN address associated with that name

These are actual transactions from my wallet:
(1)
Address: `NKNRmDTBZJuByb5HcEE6ZQ8KhCYGpt1uCPnj` which has pubkey `b77b2a3fe032357644a14d6e8f5c67a87ee8b477131ca1e47e0852638ae0e776`
Name to register: `somename`

this is the request: `{"method":"sendrawtransaction","jsonrpc":"2.0","params":{"tx":"0a340a300803122c0a20b77b2a3fe032357644a14d6e8f5c67a87ee8b477131ca1e47e0852638ae0e7761208736f6d656e616d65101412680a232104b77b2a3fe032357644a14d6e8f5c67a87ee8b477131ca1e47e0852638ae0e776ac1241408ce43787a38fefc983493de84b6cf6183e900d68c3a2df1a646efab596c956addc329e94ad89118021399f0991fdf8e898b869bf5403393b6122e04d939a720f"}}`

tx successful, with this id: `39d13910c5320ad61fac0f28cb20d97ed484d9833f8700cb6f787918f1fc4e64`

(2) After long enough wait time, I sent a request to resolve `somename`

`{"method":"getaddressbyname","jsonrpc":"2.0","params":{"name":"somename"}}`

and I received this resoponse: `{"result":"NKNGob91RtdLmxUs72UxUKPB8DhAS6qpffpB","id":"1","jsonrpc":"2.0"}`

As you can see, the address returned `NKNGob91RtdLmxUs72UxUKPB8DhAS6qpffpB` is not the same as address registered `NKNRmDTBZJuByb5HcEE6ZQ8KhCYGpt1uCPnj`

**Comment by yilunzhang** [comment] 2019-04-30 07:45
This bug seems to be caused by the 04 prefix padding added to pk on node side. This padding is supposed to be removed soon, it exists because the current code still try to be compatible with p256 pk which has a 02 or 03 prefix and length 33. The plan is to finish the following changes soon:
1. Slightly update wallet format (e.g. private key -> seed) to be consistent with Ed25519
2. Drop p256 compatibility and remove the unnecessary 04 prefix.
This problem should be completely fixed then, but we will push a quick fix to solve this specific bug even sooner.

**Comment by yilunzhang** [comment] 2019-05-01 20:47
Fixed in https://github.com/nknorg/nkn-wallet-js/pull/24
Later the 04 prefix will be removed, this fix will be a temporary solution till then.

**Closed by yilunzhang** 2019-05-01 20:47 UTC
